name = "astr-proxy"
compatibility_date = "2024-11-27"
main = "src/index.ts"

# [vars]
# OPEN_METEO_KEY = "..." # Example, though Open-Meteo is free for non-commercial
# GEOCODING_KEY = "..."

# [secrets]
# Secrets are managed via `wrangler secret put <KEY>`
